[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
eng = { path = "../eng" }
glutin = "0.27"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
bincode = "1.3"
