[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
shr = { path = "../shr" }
fxhash = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
