[package]
name = "eng"
version = "0.1.0"
edition = "2021"

[dependencies]
tree = { path = "./tree" }
ngl = { path = "../ngl" }
shr = { path = "../shr" }
image = "0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
